#### Pipeline


Data Cleaning -> Rule Based Approach -> Nlp Approach -> Brand Name

In [64]:
import pandas as pd

test_df = pd.read_csv("/Users/omkar/Documents/SmartShop/app/sains_food_cupboard.csv")

In [151]:
test_df.columns

Index(['supermarket', 'prices_(£)', 'prices_unit_(£)', 'unit', 'names', 'date',
       'category', 'own_brand'],
      dtype='str')

In [55]:
test_df.head()
prd_names = list(test_df[(test_df['own_brand'] == False)]['names'].unique())

In [56]:
len(prd_names)

6262

In [57]:
prd_names[:10]

['Maryland Cookies Chocolate Chip Minis x6',
 'Weetabix Cereal x24',
 "Walker's Shortbread Fingers x10 160g",
 'Stamford Street Co. Chopped Tomatoes in Tomato Juice 400g',
 'Cravendale Filtered Fresh Semi Skimmed Milk 2L Fresher for Longer',
 'JS Double Cream 300ml',
 'Heinz Baked Beans in a Rich Tomato Sauce 4 x 415g',
 'Walkers Ready Salted Multipack Crisps 6x25g',
 'Napolina Chopped Tomatoes 4x400g',
 'Napolina Chopped Tomatoes 400g']

In [2]:
import re

def clean_text(text):
    text = re.sub(r'\d+g|\d+kg|\d+ml|\d+L', '', text)
    text = re.sub(r'[^\w\s]', '', text)
    return text.strip()

In [49]:
KNOWN_BRANDS = ["ASDA","Sainsburys","Tesco","Morrisons"]

In [14]:
def extract_brand_hybrid(text):
    # Rule-based first
    for brand in KNOWN_BRANDS:
        if text.startswith(brand):
            return brand
    
    # Fallback to NLP
    doc = nlp(text)
    for ent in doc.ents:
        if ent.label_ == "ORG":
            return ent.text
    
    return "Unknown"

In [22]:
for name in prd_names[:10]:  # Test on first 100 names
    cleaned_name = clean_text(name)
    brand = extract_brand_hybrid(cleaned_name)
    print(f"| Cleaned: {cleaned_name} | Brand: {brand}")

| Cleaned: Maryland Cookies Chocolate Chip Minis x6 | Brand: Maryland Cookies Chocolate Chip Minis
| Cleaned: Weetabix Cereal x24 | Brand: Unknown
| Cleaned: Walkers Shortbread Fingers x10 | Brand: Unknown
| Cleaned: Sainsburys British Semi Skimmed Milk 2 4 pint | Brand: Sainsburys
| Cleaned: Sainsburys Fairtrade Bananas x5 | Brand: Sainsburys
| Cleaned: Sainsburys Red Seedless Grapes | Brand: Sainsburys
| Cleaned: Sainsburys British Free Range Eggs Large x12 | Brand: Sainsburys
| Cleaned: Sainsburys Easy Peelers Taste the Difference | Brand: Sainsburys
| Cleaned: Stamford Street Co Chopped Tomatoes in Tomato Juice | Brand: Stamford Street Co
| Cleaned: Sainsburys British Butter Salted | Brand: Sainsburys

### Extracting the package size from the name.

In [143]:
df = test_df[['names','own_brand']].copy()
df.head()

                                               names  own_brand
0           Maryland Cookies Chocolate Chip Minis x6      False
1                                Weetabix Cereal x24      False
2               Walker's Shortbread Fingers x10 160g      False
3  Sainsbury's British Semi Skimmed Milk 2.27L (4...       True
4                   Sainsbury's Fairtrade Bananas x5       True

In [144]:
import re

def clean_product_name(text):
    text = text.lower()

    # Remove patterns like "2 x 500ml"
    text = re.sub(r'\d+\s*[xX]\s*\d*\.?\d+\s*(kg|g|l|ml)', '', text)

    # Remove single weights like "500g", "1.5l"
    text = re.sub(r'\d*\.?\d+\s*(kg|g|l|ml)', '', text)

    # Remove pack info like "x6", "pack of 6"
    text = re.sub(r'(x|pack of)\s*\d+', '', text)

    # Clean extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    text = text.replace('(', '').replace(')', '')

    return text

In [145]:
df['clean_name'] = df['names'].apply(lambda x: clean_product_name(x))

In [146]:
df.head()

,names,own_brand,clean_name
0,Maryland Cookies Chocolate Chip Minis x6,False,maryland cookies chocolate chip minis
1,Weetabix Cereal x24,False,weetabix cereal
2,Walker's Shortbread Fingers x10 160g,False,walker's shortbread fingers
3,Sainsbury's British Semi Skimmed Milk 2.27L (4...,True,sainsbury's british semi skimmed milk 4 pint
4,Sainsbury's Fairtrade Bananas x5,True,sainsbury's fairtrade bananas

In [147]:
df['pack_info'] = df['names'].str.findall(r'\b\w*\d\w*\b')

In [148]:
df.head()

,names,own_brand,clean_name,pack_info
0,Maryland Cookies Chocolate Chip Minis x6,False,maryland cookies chocolate chip minis,[x6]
1,Weetabix Cereal x24,False,weetabix cereal,[x24]
2,Walker's Shortbread Fingers x10 160g,False,walker's shortbread fingers,"[x10, 160g]"
3,Sainsbury's British Semi Skimmed Milk 2.27L (4...,True,sainsbury's british semi skimmed milk 4 pint,"[2, 27L, 4]"
4,Sainsbury's Fairtrade Bananas x5,True,sainsbury's fairtrade bananas,[x5]

In [149]:
df['extracted_pack_info'] = df['names'].str.split().apply(lambda words: [w for w in words if re.search(r'\d', w)])

In [150]:
df

,names,own_brand,clean_name,pack_info,extracted_pack_info
0,Maryland Cookies Chocolate Chip Minis x6,False,maryland cookies chocolate chip minis,[x6],[x6]
1,Weetabix Cereal x24,False,weetabix cereal,[x24],[x24]
2,Walker's Shortbread Fingers x10 160g,False,walker's shortbread fingers,"[x10, 160g]","[x10, 160g]"
3,Sainsbury's British Semi Skimmed Milk 2.27L (4...,True,sainsbury's british semi skimmed milk 4 pint,"[2, 27L, 4]","[2.27L, (4]"
4,Sainsbury's Fairtrade Bananas x5,True,sainsbury's fairtrade bananas,[x5],[x5]
...,...,...,...,...,...
508709,Reese's Peanut Butter Crème Egg 5 x 34g (170g),False,reese's peanut butter crème egg,"[5, 34g, 170g]","[5, 34g, (170g)]"
508710,Sainsbury's Fig Rolls 200g,True,sainsbury's fig rolls,[200g],[200g]
508711,Sainsbury's Conchiglie (Shells) 500g,True,sainsbury's conchiglie shells,[500g],[500g]
508712,Paxo Veggie Fillers Tomato & Herb 120g,False,paxo veggie fillers tomato & herb,[120g],[120g]
508713,Sainsbury's Fresh Fruit Bitter Orange Marmalad...,True,sainsbury's fresh fruit bitter orange marmalad...,[340g],[340g]

### Extracting using the naming convention
[Brand] + [Descriptor(s)] + [Product Type] + [Variant] + [Size/Unit]

In [161]:
### Introducing brand column and replacing know brands wih their names and unknown with "Unknown".

df['own_brand'].where(df['own_brand'] == True, "sainsburys")

0         sainsburys
1         sainsburys
2         sainsburys
3               True
4               True
             ...
508709    sainsburys
508710          True
508711          True
508712    sainsburys
508713          True
Name: own_brand, Length: 508714, dtype: object

In [163]:
df[df['own_brand'] == True]

,names,own_brand,clean_name,pack_info,extracted_pack_info
3,Sainsbury's British Semi Skimmed Milk 2.27L (4...,True,sainsbury's british semi skimmed milk 4 pint,"[2, 27L, 4]","[2.27L, (4]"
4,Sainsbury's Fairtrade Bananas x5,True,sainsbury's fairtrade bananas,[x5],[x5]
5,Sainsbury's Red Seedless Grapes 500g,True,sainsbury's red seedless grapes,[500g],[500g]
6,Sainsbury's British Free Range Eggs Large x12,True,sainsbury's british free range eggs large,[x12],[x12]
7,"Sainsbury's Easy Peelers, Taste the Difference...",True,"sainsbury's easy peelers, taste the difference",[600g],[600g]
...,...,...,...,...,...
508707,Sainsbury's Roasted Salted Pistachios 300g,True,sainsbury's roasted salted pistachios,[300g],[300g]
508708,Sainsbury's Roasted Pistachios in Shells 270g,True,sainsbury's roasted pistachios in shells,[270g],[270g]
508710,Sainsbury's Fig Rolls 200g,True,sainsbury's fig rolls,[200g],[200g]
508711,Sainsbury's Conchiglie (Shells) 500g,True,sainsbury's conchiglie shells,[500g],[500g]
508713,Sainsbury's Fresh Fruit Bitter Orange Marmalad...,True,sainsbury's fresh fruit bitter orange marmalad...,[340g],[340g]

In [167]:
df['own_brand'].value_counts()

own_brand
False    373525
True     135189
Name: count, dtype: int64

In [173]:
df['brand'] = df['own_brand'].replace({True: "sainsburys", False: "Unknown"})

In [174]:
df.head()

,names,own_brand,clean_name,pack_info,extracted_pack_info,brand
0,Maryland Cookies Chocolate Chip Minis x6,False,maryland cookies chocolate chip minis,[x6],[x6],Unknown
1,Weetabix Cereal x24,False,weetabix cereal,[x24],[x24],Unknown
2,Walker's Shortbread Fingers x10 160g,False,walker's shortbread fingers,"[x10, 160g]","[x10, 160g]",Unknown
3,Sainsbury's British Semi Skimmed Milk 2.27L (4...,True,sainsbury's british semi skimmed milk 4 pint,"[2, 27L, 4]","[2.27L, (4]",sainsburys
4,Sainsbury's Fairtrade Bananas x5,True,sainsbury's fairtrade bananas,[x5],[x5],sainsburys

In [175]:
df['brand'].value_counts()

brand
Unknown       373525
sainsburys    135189
Name: count, dtype: int64

In [41]:
for name in prd_names[:10]:  # Test on first 100 names
    cleaned_name = clean_text(name).split()[:3]
    print(cleaned_name)

['Maryland', 'Cookies', 'Chocolate']
['Weetabix', 'Cereal', 'x24']
['Walkers', 'Shortbread', 'Fingers']
['Sainsburys', 'British', 'Semi']
['Sainsburys', 'Fairtrade', 'Bananas']
['Sainsburys', 'Red', 'Seedless']
['Sainsburys', 'British', 'Free']
['Sainsburys', 'Easy', 'Peelers']
['Stamford', 'Street', 'Co']
['Sainsburys', 'British', 'Butter']

In [35]:
len(prd_names[1].split())

3

In [189]:
df[df['own_brand'] == False]['clean_name'].str.split().apply(lambda x: x[:1]).astype(str)

0           ['maryland']
1           ['weetabix']
2           ["walker's"]
8           ['stamford']
12        ['cravendale']
               ...
508703        ['truvia']
508704      ['ambrosia']
508706        ['quaker']
508709       ["reese's"]
508712          ['paxo']
Name: clean_name, Length: 373525, dtype: str

In [196]:
df[df['own_brand'] == False]['clean_name'] \
    .str.split() \
    .str[0:3].value_counts().head(20)

clean_name
[cadbury, dairy, milk]         3250
[stamford, street, co.]        3138
[old, el, paso]                3037
[quaker, oat, so]              2524
[tilda, microwave, rice]       1712
[the, spice, tailor]           1603
[batchelors, cup, a]           1551
[heinz, baked, beans]          1445
[taylors, of, harrogate]       1126
[pip, &, nut]                  1053
[lee, kum, kee]                1036
[hartley's, 10, cal]            959
[batchelors, pasta, 'n']        917
[kellogg's, special, k]         881
[kellogg's, rice, krispies]     873
[john, west, tuna]              851
[lindt, excellence, dark]       842
[heinz, cream, of]              822
[knorr, stock, pot]             800
[princes, tuna, chunks]         792
Name: count, dtype: int64

#### Hybrid System 

- Dictionary match (fast win):
    
        If match => return

- ML/NER model: 

        If no match  => predict
- Fallback rule:

        First 1–2 tokens

### Creating a Dictionary:

To Create a Dictionary We need to Extract the common known brands manually to create additional data.

In [194]:
df[df['own_brand'] == False]['clean_name'] \
    .str.split() \
    .str[0].nunique()

942

There are 942 unique brands in Food Cupboard Data Itself

In [197]:
#### Generating n-gramns:
from collections import Counter

def generate_ngrams(names, n):
    ngrams = []
    
    for name in names:
        tokens = name.split()
        if len(tokens) >= n:
            ngrams.append(" ".join(tokens[:n]))
    
    return ngrams

In [198]:
#Count frequency
names = df['clean_name'].dropna().str.lower()

one_word = Counter(generate_ngrams(names, 1))
two_word = Counter(generate_ngrams(names, 2))
three_word = Counter(generate_ngrams(names, 3))

In [209]:
# Inspect top candidates
one_word.most_common(35)

[("sainsbury's", 135189),
 ('heinz', 11721),
 ('cadbury', 10490),
 ('lindt', 5558),
 ('walkers', 5339),
 ("kellogg's", 5226),
 ('batchelors', 5059),
 ('twinings', 4567),
 ("mcvitie's", 4151),
 ('john', 4073),
 ('dr.', 4034),
 ('the', 3981),
 ("hartley's", 3799),
 ('quaker', 3549),
 ('baxters', 3276),
 ('old', 3243),
 ('stamford', 3188),
 ('princes', 3150),
 ("jacob's", 3107),
 ('fudco', 2890),
 ('ambrosia', 2866),
 ('tilda', 2766),
 ("nando's", 2591),
 ('dolmio', 2527),
 ('napolina', 2411),
 ('extra', 2389),
 ('loyd', 2297),
 ("colman's", 2138),
 ('knorr', 2137),
 ("sharwood's", 2082),
 ('bonne', 2007),
 ('nescafé', 1999),
 ('kinder', 1978),
 ('starbucks', 1950),
 ('graze', 1946)]

In [203]:
two_word.most_common(20)

[('john west', 4073),
 ('dr. oetker', 3942),
 ('cadbury dairy', 3250),
 ('stamford street', 3188),
 ('old el', 3037),
 ('quaker oat', 2889),
 ("sainsbury's fairtrade", 2778),
 ('loyd grossman', 2297),
 ('bonne maman', 2007),
 ('tilda microwave', 1858),
 ("tony's chocolonely", 1800),
 ("sainsbury's deliciously", 1784),
 ("sainsbury's ground", 1763),
 ("sainsbury's sweet", 1730),
 ("sainsbury's tomato", 1682),
 ("sainsbury's ready", 1615),
 ('the spice', 1603),
 ('lindt lindor', 1585),
 ('heinz baked', 1579),
 ("sainsbury's italian", 1574)]

In [204]:
three_word.most_common(20)

[('cadbury dairy milk', 3250),
 ('stamford street co.', 3138),
 ('old el paso', 3037),
 ('quaker oat so', 2524),
 ("sainsbury's deliciously free", 1784),
 ('tilda microwave rice', 1712),
 ('the spice tailor', 1603),
 ('batchelors cup a', 1551),
 ('heinz baked beans', 1445),
 ("sainsbury's free from", 1375),
 ("sainsbury's ready to", 1260),
 ('taylors of harrogate', 1126),
 ("sainsbury's milk chocolate", 1063),
 ('pip & nut', 1053),
 ('lee kum kee', 1036),
 ("hartley's 10 cal", 959),
 ("batchelors pasta 'n'", 917),
 ("sainsbury's tomato &", 908),
 ("kellogg's special k", 881),
 ("kellogg's rice krispies", 873)]

In [210]:
## Keep Top N (filter noise)
TOP_N = 3

top_1 = set([x[0] for x in one_word.most_common(TOP_N)])
top_2 = set([x[0] for x in two_word.most_common(TOP_N)])
top_3 = set([x[0] for x in three_word.most_common(TOP_N)])

In [224]:
one_word.get("dr.")

4034

In [225]:
two_word.get("dr. karg")

In [228]:
two_word.get("dr. karg's")

92

In [227]:
df[df['clean_name'].str.startswith('dr')]['clean_name'].value_counts().head(20)

clean_name
dr. oetker milk chocolate chip chunks                92
dr. oetker 70% extra dark chocolate chip chunks      92
dr. oetker platinum grade leaf gelatine              92
dr. oetker gelatine sachets                          92
dr. oetker ready to roll white soft fondant icing    92
dr. oetker ready to roll fondant icing               92
dr. oetker extra strong red food colouring gel       92
dr. oetker extra strong green food colouring gel     92
dr. oetker extra strong blue food colouring gel      92
dr. karg's pumpkin seeds protein thins               92
dr. oetker extra strong orange food colouring gel    92
dr. oetker giant chocolate stars                     92
dr. oetker rainbow decorating icing                  92
dr. oetker extra strong pink food colouring gel      92
dr. oetker vege-gel gelatine sachets                 92
dr. oetker extra strong yellow food colouring gel    92
dr. oetker extra strong violet food colouring gel    92
dr. oetker extra strong black food colouring gel     92
dr. oetker bright & bold sprinkles mix               92
dr. oetker chocolate hearts                          92
Name: count, dtype: int64

## Selection Logic

In [229]:
from collections import defaultdict

prefix_next_map = {
    1: defaultdict(list),
    2: defaultdict(list),
    3: defaultdict(list)
}

names = df['clean_name'].dropna().str.lower()

for name in names:
    tokens = name.split()
    
    for n in [1, 2, 3]:
        if len(tokens) > n:
            prefix = " ".join(tokens[:n])
            next_token = tokens[n]
            
            prefix_next_map[n][prefix].append(next_token)

In [230]:
import pandas as pd

def compute_scores(prefix_map):
    data = []
    
    for n in prefix_map:
        for prefix, next_tokens in prefix_map[n].items():
            freq = len(next_tokens)
            diversity = len(set(next_tokens))
            
            score = freq * (diversity + 1)  # simple scoring
            
            data.append({
                "prefix": prefix,
                "n": n,
                "freq": freq,
                "diversity": diversity,
                "score": score
            })
    
    return pd.DataFrame(data)

score_df = compute_scores(prefix_next_map)

In [264]:
score_df.sort_values(by="percentile", ascending=False).head(25)

                     prefix  n    freq  diversity     score  percentile
3               sainsbury's  1  135189        668  90441441  100.000000
7                     heinz  1   11721         54    644655   99.988676
22                  cadbury  1   10490         52    555970   99.977353
167                twinings  1    4567         38    178113   99.966029
8                   walkers  1    5339         27    149492   99.954705
1714             dr. oetker  2    3942         35    141912   99.943381
291                   fudco  1    2890         48    141610   99.932058
45                kellogg's  1    5226         23    125424   99.920734
13                mcvitie's  1    4151         29    124530   99.909410
4305    stamford street co.  3    3138         34    109830   99.898086
42                    lindt  1    5558         18    105602   99.886763
4341     cadbury dairy milk  3    3250         28     94250   99.875439
1669              john west  2    4073         18     77387   99.864115
944   sainsbury's fairtrade  2    2778         25     72228   99.852791
147                 baxters  1    3276         20     68796   99.841468
17               batchelors  1    5059         12     65767   99.830144
138                     the  1    3981         15     63696   99.818820
96                hartley's  1    3799         15     60784   99.807496
16                  jacob's  1    3107         18     59033   99.796173
14                  princes  1    3150         16     53550   99.784849
4449            old el paso  3    3037         16     51629   99.773525
9                  napolina  1    2411         19     48220   99.762201
499                   natco  1    1542         29     46260   99.750878
300                 cofresh  1    1640         27     45920   99.739554
25                 ambrosia  1    2866         15     45856   99.728230

In [258]:
score_df['percentile'] = score_df['score'].rank(pct=True)
score_df['percentile'] = score_df['percentile'] * 100

In [272]:
score_df['percentile_within_n'] = score_df.groupby('n')['score'].rank(pct=True)

In [275]:
score_df[(score_df['percentile_within_n'] > 0.9) & (score_df['diversity'] > 15)]

,prefix,n,freq,diversity,score,percentile,percentile_within_n
3,sainsbury's,1,135189,668,90441441,100.000000,1.000000
7,heinz,1,11721,54,644655,99.988676,0.998937
8,walkers,1,5339,27,149492,99.954705,0.995749
9,napolina,1,2411,19,48220,99.762201,0.984060
11,alpro,1,1250,21,27500,99.524403,0.970244
12,ktc,1,1270,24,31750,99.614993,0.973433
13,mcvitie's,1,4151,29,124530,99.909410,0.992561
14,princes,1,3150,16,53550,99.784849,0.985122
16,jacob's,1,3107,18,59033,99.796173,0.986185
22,cadbury,1,10490,52,555970,99.977353,0.997875
42,lindt,1,5558,18,105602,99.886763,0.991498
45,kellogg's,1,5226,23,125424,99.920734,0.993624
86,rowse,1,1483,16,25211,99.479108,0.968119
93,haribo,1,1877,21,41294,99.682935,0.976621
106,nairn's,1,1479,16,25143,99.456460,0.967056
135,sharwood's,1,2082,19,41640,99.705583,0.978746
139,patak's,1,1442,16,24514,99.422489,0.963868
147,baxters,1,3276,20,68796,99.841468,0.990436
167,twinings,1,4567,38,178113,99.966029,0.996812
256,whitworths,1,1705,19,34100,99.648964,0.975558
284,starbucks,1,1950,21,42900,99.716906,0.979809
291,fudco,1,2890,48,141610,99.932058,0.994687
300,cofresh,1,1640,27,45920,99.739554,0.981934
309,odysea,1,1882,21,41404,99.694259,0.977683
499,natco,1,1542,29,46260,99.750878,0.982997
944,sainsbury's fairtrade,2,2778,25,72228,99.852791,0.999405
1131,bonne maman,2,2007,19,40140,99.671611,0.999107
1152,sainsbury's mixed,2,1501,16,25517,99.490431,0.997321
1211,merchant gourmet,2,1315,20,27615,99.547050,0.998214
1267,sainsbury's ground,2,1763,16,29971,99.581021,0.998511
1396,blue dragon,2,1469,22,33787,99.637640,0.998809
1669,john west,2,4073,18,77387,99.864115,0.999702
1714,dr. oetker,2,3942,35,141912,99.943381,1.000000
1765,dunn's river,2,1007,17,18126,99.196014,0.994641
2008,ben's original,2,1168,18,22192,99.365870,0.996428
2110,twinings superblends,2,1167,19,23340,99.388518,0.996725
2243,sainsbury's flourish,2,1097,16,18649,99.218662,0.994939
4305,stamford street co.,3,3138,34,109830,99.898086,1.000000
4341,cadbury dairy milk,3,3250,28,94250,99.875439,0.999779
4342,tilda microwave rice,3,1712,16,29104,99.569698,0.999117
4449,old el paso,3,3037,16,51629,99.773525,0.999559
4518,sainsbury's milk chocolate,3,972,16,16524,99.150719,0.998455
5435,the spice tailor,3,1603,17,28854,99.558374,0.998896
5733,lee kum kee,3,1036,19,20720,99.263957,0.998676
6267,sainsbury's free from,3,1375,27,38500,99.660288,0.999338

In [278]:
def select_non_overlapping_brands(score_df):
    df = score_df.copy()
    
    # use strongest signal
    df = df.sort_values(by='percentile', ascending=False)
    
    selected = []
    
    for _, row in df.iterrows():
        candidate = row['prefix']
        
        # check if already covered by higher ranked brand
        if any(
            candidate == s or candidate.startswith(s) or s.startswith(candidate)
            for s in selected
        ):
            continue
        
        selected.append(candidate)
    
    return selected

In [279]:
result = select_non_overlapping_brands(score_df)

for r in result:
    print(r)

sainsbury's
heinz
cadbury
twinings
walkers
dr. oetker
fudco
kellogg's
mcvitie's
stamford street co.
lindt
john west
baxters
batchelors
the
hartley's
jacob's
princes
old el paso
napolina
natco
cofresh
ambrosia
starbucks
sharwood's
odysea
haribo
bonne maman
whitworths
blue dragon
colman's
ktc
graze
nando's
tilda microwave rice
merchant gourmet
loyd grossman
alpro
extra
rowse
nairn's
homepride
mutti
patak's
oxo
knorr
yutaka
ben's original
betty crocker
kinder
quaker
lavazza
lee kum kee
hellmann's
branston
itsu
kenco
dunn's river
dolmio
doritos
bisto
pot noodle
fox's
maltesers
weetabix
nescafé
capsicana
nomo
grace
tyrrells
jordans
kallo
tony's chocolonely
galaxy
wright's
kp
taylors of harrogate
naked
maggi
reese's
nissin soba
laila
dole
mccoy's
pringles
kitkat
sauce shop
aero
eat natural
belvita
nature valley
nakd
sacla
billington's
sarson's
bear
del monte
dorset cereals
forest feast
filippo berio
ryvita
organix
smarties
nature's finest
marmite
maynards bassetts
nestle
de cecco
bahlsen
milkybar
swizzels
pip & nut
deliciously ella
ainsley harriott
pizza express
canderel
sainsbury’s
fray bentos
leon
house of cake
bens original
tetley
rubicon
paxo
kit kat
go ahead
lotus biscoff
mcdougalls
hp
ocean spray
l'or
schär gluten free
ferrero
m&m's
pukka
ritter sport
osem
trek
cirio
moo free
sensations
doves farm organic
polish specialities
rowntree's
east end
options
freee gluten free
candy kittens
tassimo
garner's
nielsen-massey
newman's own
green
monster energy
just spices
oshee
very lazy
veetee
pipers
al'fez
tic tac
kikkoman
belazu
costa coffee
schar gluten free
nescafe
carr's
teapigs
hula hoops
alpen
buttermilk
tate & lyle
thorntons
border
aunt bessie's
barilla
kabuto noodles
mrs elswood
skittles
rowntree’s
capri-sun
popchips
st. dalfour
butterkist
yorkie
love corn
mackays
carnation
terry's chocolate orange
peter's yard
askeys
crosta & mollica
encona
whole earth
urban fruit
snack a jacks
sour patch kids
mentos
nutella
lu le petit
kubus
fentimans classic
properchips
plant pioneers
oreo
werther's original
fuel10k
monty bojangles
mug shot
fridge raiders
lily o'brien's
regal
yorkshire tea
carousel
good
rakusen's
manilife
union
jamie oliver
ye olde oak
meridian
mr kipling
allinson
fruit bowl
maryland
jude's
dino's famous
toblerone
angel delight
opies
fruittella
tropical sun
silver spoon
bio&me
white rabbit
morliny
walker's
clipper fairtrade
califia farms
aunty's
truvia
trebor
eat real
frylight 1 cal
jaimin
shreddies the
lizi's
gefen
snickers
la espanola
propercorn
amoy
naturya
oatly
clipper organic
peperami
bio & me
gallo
chicken tonight
wagamama
fareshare
tribe
munchies
milky way
cake
gran luchito
genius gluten free
carte noire
aspall
want want
fulfil chocolate
mazzetti
kettle chips
bolands
jack link's
island sun
cafedirect
robertson's
twix
violife
illy
idahoan perfect
nongshim
tracklements recipe no.
sun
jammie dodgers
littleover
mars
ritz
fibre one
lyle's
soreen
elephant atta
crave
prymat
kohinoor
ko-lee
monin
plenish organic
tick tock
tiptree
guinness
ricola sugar free
stagg
yum & yay
karyatis
guylian
red's
stokes
thomas fudge's
frank cooper's
maoam
spam
polo
bird's
gia
huel
mccain
maille
tariq halal
menier swiss
quorn vegetarian
sosu
elizabeth shaw
horlicks
kedem
airwaves
bfree
kind protein
kellogg’s
potts'
tunnock's
yo!
linwoods
rajah
clarks
promise gluten free
yeo valley organic
mighty
warburtons gluten free
sainsburys
krakus
yeo's
virtu
loacker
wikinger
hermesetas
glenryck pilchards in
ortiz
nissin demae ramen
douwe egberts
jus-rol
crazy jack organic
food thoughts
saxa
indo mie
nurishment the original
ovaltine
pg tips
tilda kids
mrs crimble's
thai taste
sweet
telma
e. wedel
moma
rhythm108 swiss
mr porky
tiger
marigold
pure
goldenfry original
sokolow
hershey's cookies
cornish
siro
tilda pure basmati
shredded wheat
geeta's
quality street
ueshima coffee company
hip pop
js
after eight
tabasco
dairy
ka sparkling
blue riband
kucharek
montezuma's
fybocalm
vitasoy
s&b
haagen-dazs
cantina
mlekpol
ben's plant powered
paskesz sour
humza
eazypop microwave popcorn
cheetos puffs
h!p
hi-chew
old jamaica
judes
hunger breaks
summer pride
grant's
goong instant soup
jif lemon
nissin cup noodles
splenda
scott's porage
parsons
gourmet burger kitchen
hovis
mazola pure
atora
carrs breadmaker
bendicks
off
maldon
barny
mornflake
clif bar
budweiser
santa
chippa
pamapol
magnum
tuscanini
penn state
wagon wheels
popworks
bovril beef
island delight
duerr's
edlers
garden cream wafers
tymbark
wasabi
farrington's mellow yellow
mieszko
fry's
flora
toffee crisp
fruit shoot
daddies
patak’s
osu
cape herb
suhana
lazy day foods
taylor & colledge
flahavan's
capri sun
surreal
up
mama instant
yorkshire gold
pom-bear
shan
skips prawn
libeert
bold bean co
bigga
trophy
la chinata smoked
sea
discos
weight watchers
mary berry's
buckwud
baileys chocolate
najma
wrigley's
hilltop
supermalt
treat kitchen
flying goose
serious pig
cheerios
howdah
birds eye
genius dgf
taste
levi roots
tilda wholegrain
riso
kind maple pecan
kumana avocado hot
lea
crisp
kirsty's
wonderful roasted salted
little's
celebrations
herdez
kind peanut butter
koh-kae
dolce gusto
big hoops
rhythm 108
nature's heart
gressingham
mega monster munch
tony’s chocolonely milk
nesquik
pot pasta
heck
frugo
royal
kotlin
dr karg organic
schär gluten-free
koko
creative nature
ensure nutrivigor
krasnystaw
sodastream
alara
bacofoil
raw
vadasz
go free
kinnerton
kurkure
mallow & marsh
mae ploy
mister free'd
dega
smiths
proper chips
tingly ted’s
slimfast
mcdonnells
grzeski
village pride
ottogi
magija
yan yan
milka
goldfish brand
achva
manomasa
perkier
rymut
goralki
jutrzenka
skinny whip
manischewitz
pepsi max
halva
whitby
witpak
kolee instant noodles
rice
proper corn sweet
galbani
wonka
raise clusters of
aleyna
king
japanese style mochi
choccie dodgers
miso tasty organic
providence
stoats
simply delish zero
britannia good day
piatnica
epic
oggs
mahi
bare naked
ginbis dream animals
laciate
il casolare
kind dark chocolate
doisy & dam
clearspring organic
rude health
fanta
lancashire farm
booja-booja organic chocolate
kind caramel almond
lowicz
frank's
innocent
petits filous
nairns gluten free
tahira
nuii
mr.
milo instant malt
mike and ike
healthy boy brand
profi poultry
tayto
niru
kind fruit &
clarence court
aunty noray's
hubbard's
kind chocolate chip
rombouts coffee filter
akash gold
kabuto mac &
nature's path
barebells protein milkshake
world
mlekovita
starburst vegan
fullgreen
jack daniel's
merba
hillfarm extra virgin
foresight
tulip
ballymaloe original
premium belgian
iliada extra
kelloggs
pura refined vegetable
mrs balls original
top taste
brooklyn dino's
rolo
farrow's giant marrowfat
storck toffifee
snack organisation
proper sea
malay taste kicap
flipz milk
jubel
smint
makrut
jimjams
arden
cardini's
blue food
baxter's vegetarian honeyed
delecta karpatka
tilda microwave mushroom
olivio
xxx
harley's
bart
certo
raffaello coconut and
chupa
patum
paw
honey
malt o meal
bunlimited
wilkin
surprise egg with
tilda boil in
dr. karg's pumpkin
daim
malted milk
curiously
pieminister gluten free
maxi nutrition maxwhey
thatchers
tony's chocolonel chocolate
losalt
hartley’s
skippy
post
mikado
rose's lemon &
o'kane
tidman's
mori-nu silken tofu
nik
panda
lion
tuc crackers savoury
ready
total
hengstenberg
cookie
pek
nem
ambassador
lyons
bosh!
nature's store hazelnut
bull's-eye original bbq
tilda fragrant
riesen chewy toffee
stute
cerebos
la doria
wheat
limited
caxton pink
finn crisp
lazyday
carotino red palm
alfa
tracker oats
doria
squares chocolatey
sesame snaps
krisprolls
misfits plant powered
cholula original
daily's
mohapx
l'oasis
sharwoods
cerelac infant cereals
charlie bigham's
oddpods
kiddylicious
fish!
boostball
hellmann’s
too good
happy egg
fever
henderson's
inferno horseradish no
campbell's
supligen
l’or
diet
tarczynski
french's classic yellow
drink
old speckled hen
black
ors hydration
tea india masala
lift lemon tea,
azeem halal
mellow bird's
oliveira
jubbly ice lollies
lajkonik pretzel salty
select
paterson's
ribena no added
cafédirect
hubbard’s foodstore peeled
vici premium
weetos chocolatey
freee organic gluten
via roma
ella's kitchen
free and
milk easter
pots
10 in. round
doves farm wholemeal
double dipped
simon howie
roi thai
pride lemon
irish yogurts diet
vifon golden
tilda microwave caribbean
reese’s peanut butter
horalky
barry's tea
natural
pasieka multiflower
vita lemon
camp chicory
thomy
kielecki
winiary
daura damm lager
terry’s chocolate orange
ayoola pounded
jbb hot
bakery
ardealul pork
lotte pepero
chase
simplee aloe
grenade carb killa
taffel
lorenz crunchips
zhitnica
halo top
schweppes
akuku
lubella little
nando’s
hu hazelnut butter
ghee
polish grated
irwin's together soda
franks redhot buffalo
thai dragon
jezyki classic
vita chrysanthemum tea
fentimans dandelion &
lungkow
excelsior
pink
peroni nastro azzurro
liberty easy
przysnacki bacon
felix sunflower
puck
pimlico confectioners
tropical vibes
nudders chocovered salty
basics 12
red bull
hu cashew butter
dr pepper
north
carapelli organic extra
nutri-brex gluten free
willy's organic live
brunswick
golden fluff microwave
whole creations
bon chancecheese
elephant medium
muszynianka green
granovita organic
estrella sourcream &
slush
hu almond
bangthai sriracha chilli
pop tarts
kettle sea salt
doves farm gluten
galipette
spichlerz
piriteze allergy &
graham's
pyrex
nishiki medium grain
wedel aha sesame
bikaji bombay
san pellegrino sparkling
sizzola air fryer
st marys banana
space
squid brand
henry
prince polo classic
gavinatura heartburn &
reign
kimura japanese lemonade
tabitha's chin chin,
jolly rancher
polish marinated red
la monegasque anchovy
orgran no egg
olivado avocado
ufc refresh
sodziaus green
mai thai
yayu
proper flame
familijne cocoa cream
brown
holy moly
taijade
proper prawn
fentimans ginger
selga classic
klik
calbee
desi paneer
baldwins sarsaparilla
jord organic
fabulous freefrom
tate + lyle
sawanotsuru
fentimans rose
montezuma’s organic
jelly belly
henna very
dunns
warburtons tiger artisan
baron herzog
squeaky bean potato&onion
ting grapefruit
cawston apple &
palwin no.
goldenfry gravy
beanies
lingham's chilli
tilda everyday
milko
steinhauer opiata marinated
naturli vegan
gü
risana
n?kd protein
ginsters gluten
salaam
fentimens
stork
cheezees
mrs. crimble's
lucy bee
vitamin b12
graal mackerel fillets
costa hot
noiving kombucha
bute
kerrygold pure
mccanns irish rich
breakaway
pakeeza
bepps black eyed
relentless raspberry zero
schar white wholesome
zott
garnier
wringley's extra ice
mango
nash red
coffee
maple crest maple
shuang renhsu biang
crayola decorate
vita coco coconut
angelic
vivera plant
n?kd. banoffee pie
lazy day free
bluey milk
schär wholesome
bernard matthews turkey
food heaven
kirstys lentil cottage
haliborange omega-3
renshaw royal
crabbie's
pick up salted
almondy almond
chocalot
m&m’s giant
aroy-d
taj mogo
lily o’brien’s
wholecreations dairy
specialite locale sultana
fulfil peanut
gge wheat crackers
thortons classic milk
cauldron vegan
shuangrenhsu
rhythm108 double
arla jord chilled
ristorante
odlums irish white
difatti gluten free
tala
jfc
foco coconut
vitalite
milupa
calypso
orion choco
value
spécialité locale sultana
ramona's original
bounty
africa's
kenko
satonoyuki
cidona sparkling
mokko brown
party
richmond meat free
special k crunchy
fybogel
scrambled oggs plant
koikeya kara mucho
chef
spicy yuzu
pulsin
j-basket seaweed crisps
rhythmluten free
ben &
baking buddy
mr freeze sugar

In [283]:
def grouped_clean_output(score_df):
    selected = select_non_overlapping_brands(score_df)
    
    output = {"1-word": [], "2-word": [], "3-word": []}
    
    for s in selected:
        n = len(s.split())
        output[f"{n}-word"].append(s)
    
    return output

gco = grouped_clean_output(score_df)

In [307]:
"dr. karg" in gco.get("2-word")

False

In [309]:
#### Creating a final list of brands to test on the data
final_brands = set(gco.get("1-word", []) + gco.get("2-word", []) + gco.get("3-word", []))

In [321]:
def fill_brand(row, brands_set):
    if row['brand'] != 'Unknown':
        return row['brand']
    
    text = row['clean_name'].lower()
    
    # check multi-word first (important)
    for brand in sorted(brands_set, key=lambda x: -len(x.lower().split())):
        if brand in text:
            return brand
    
    return 'unknown'

In [323]:
brands_set = set(final_brands)
df['own_brand'] = df.apply(lambda row: fill_brand(row, brands_set), axis=1)

In [328]:
df.to_csv("/Users/omkar/Documents/SmartShop/notebook/nlp_output.csv", index=False)

In [327]:
df['own_brand'].value_counts()

own_brand
sainsburys                 135405
up                          18468
sweet                        9062
coffee                       8259
crisp                        7172
                            ...
ben &                           5
j-basket seaweed crisps         5
rhythmluten free                5
baking buddy                    4
mr freeze sugar                 3
Name: count, Length: 931, dtype: int64

In [335]:
bad_words = {"in", "of", "to", "for", "and", "with","up",'cookies'}

brands_set = {b for b in brands_set if b not in bad_words and len(b) > 2}

In [346]:
### Cleaning the text.

import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r"[^\w\s]", "", text)
    return text

cleaned = clean_text(df['clean_name'].iloc[0])
print(cleaned)

maryland cookies chocolate chip minis

In [ ]:
score_map = dict(zip(score_df['prefix'], score_df['score']))
score_map

In [347]:
def get_all_matches(text, brands_set):
    matches = []
    
    for brand in brands_set:
        pattern = r'\b' + re.escape(brand) + r'\b'
        
        if re.search(pattern, text):
            matches.append(brand)
    
    return matches

matches = get_all_matches(cleaned, brands_set)
print(matches)

['maryland']

In [350]:
for m in matches:
    print(m, score_map.get(m, 0))

maryland 2155

In [351]:
def filter_matches(matches):
    return [m for m in matches if len(m) > 2]

filtered = filter_matches(matches)
print(filtered)

['maryland']

In [352]:
def get_position(text, brand):
    return text.find(brand)

for m in matches:
    print(m, get_position(cleaned, m))

maryland 0

In [353]:
def select_best_match(matches, text, score_map):
    if not matches:
        return None
    
    def score_fn(m):
        position = text.find(m)
        score = score_map.get(m, 0)
        
        return (
            -position,          # earlier is better
            score,              # higher is better
            len(m.split())      # longer is better
        )
    
    return max(matches, key=score_fn)

best = select_best_match(matches, cleaned, score_map)
print(best)

maryland

In [355]:
##### Debuging function

def debug_brand_extraction(text, brands_set, score_map):
    if not isinstance(text, str):
        return None, 0
    
    cleaned = clean_text(text)
    
    matches = get_all_matches(cleaned, brands_set)
    
    if not matches:
        return None, 0
    
    best = select_best_match(matches, cleaned, score_map)
    
    score = score_map.get(best, 0)
    
    return best, score

In [356]:
debug_df = df[['clean_name']].copy()

debug_df[['matched_brand', 'brand_score']] = debug_df['clean_name'].apply(
    lambda x: pd.Series(debug_brand_extraction(x, brands_set, score_map))
)

KeyboardInterrupt:

In [ ]:
debug_df.head(20)

In [1]:
from nltk import pos_tag, word_tokenize
pos_tag(word_tokenize("John's big idea isn't all that bad."))

LookupError:
**********************************************************************
  Resource 'punkt_tab' not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load 'tokenizers/punkt_tab/english/'

  Searched in:
    - '/Users/omkar/nltk_data'
    - '/Users/omkar/Documents/SmartShop/.venv/nltk_data'
    - '/Users/omkar/Documents/SmartShop/.venv/share/nltk_data'
    - '/Users/omkar/Documents/SmartShop/.venv/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************